### ISSUE TITLE
Doubts with a function

### ISSUE THREAD

**Issue by freyvaz92** [wcmbishop/rayshader-demo#1]
Dear Will,
I was reviewing your work titled: "I can rayshade, and so can you", and I have a issue with the function "define_image_size". What package does it belongs to or is it a function that you created? 
If it's the second option where can I find it?

Thank you for your time and I look forward to hearing from you 

Best regards 
Francisco Reyes-Vázquez

**Comment by wcmbishop** [comment]
Hi Fancisco, thanks for the note. That has been a point of confusion for a few other folks as well.

That function, and several others, are custom functions I wrote for the article. To use them, you will need to source the function definitions locally. Check out the calls to `source()` in the `code-samples.R` file in the repo. You will need to either download a copy of the repo, or you can copy-paste the function definitions (from the scripts in the `R` folder) onto your machine.

To help clarify this in the article, I added an additional note in the "Setup" section, and I added a special subscript to each "local" function to let people know it's custom. I also added links for each function to the source `.R` file. Check out the updated article now.

Hope that clears things up!
